spring:
  application:
    name: fhs-ai-agent
  ai:
    dashscope:
      api-key: sk-9be1415d68284ad589cc06c9dbb5b839
      chat:
        options:
          model: qwen-turbo
    ollama:
      base-url: http://localhost:11434
      chat:
        model: "gemma3:1b"
#  datasource:
#    url: jdbc:postgresql://rm-cn-0yc4ovsva0003aso.rwlb.rds.aliyuncs.com:5432/fhs_ai_agent
#    username: my_user
#    password: Fhs596702588!
#    driver-class-name: org.postgresql.Driver

search-api:
  api-key: nKgFKfquV941xPySw6zGCa5g
